Repository quark-engine/quark-engine, pull requests merged in 2020-03, with the labels that each got.

#47 fix typo 'RuleoOject' to 'RuleObject'
  docs/source/quark_inside_objects.rst
Labels: TYPO

#51 fixes bug issue in #50
  quark/Objects/xrule.py
Labels: bug

#54 Make empty list comparisons more Pythonic, fixes #53
  quark/Evaluator/pyeval.py
  quark/Objects/apkinfo.py
  quark/Objects/xrule.py
Labels: enhancement
