Repository quark-engine/quark-engine, pull requests merged in 2022-09, with the labels that each got.

#377 Add Quark Script APIs to detect CWE-89
  quark/script/__init__.py
  tests/script/rules/00193.json
  tests/script/test_script.py
Labels: pr-processing-state-04

#379 Add Quark Script APIs to detect CWE-926
  quark/core/apkinfo.py
  quark/core/axmlreader/__init__.py
  quark/core/interface/baseapkinfo.py
  quark/core/rzapkinfo.py
  quark/script/__init__.py
  tests/conftest.py
  tests/core/test_apkinfo.py
  tests/core/test_axmlreader.py
  tests/script/test_script.py
Labels: pr-processing-state-06

#383 Update document for Quark Script CWE-749
  README.md
  docs/source/quark_script.rst
Labels: pr-processing-state-05

#381 Add Quark Script APIs to detect CWE-749
  quark/core/apkinfo.py
  quark/core/quark.py
  quark/core/rzapkinfo.py
  quark/evaluator/pyeval.py
  quark/script/__init__.py
  quark/script/utils.py
  quark/utils/tools.py
  tests/core/test_apkinfo.py
  tests/core/test_quark.py
  tests/evaluator/test_pyeval.py
  tests/script/test_script.py
  tests/utils/test_tools.py
Labels: pr-processing-state-05

#384 Fix missing words/lines in the Quark Script document
  docs/source/quark_script.rst
Labels: pr-processing-state-05

#387 Update the member page
  docs/source/contribution.rst
Labels: pr-processing-state-05

#388 Update version number to v22.9.1
  quark/__init__.py
Labels: pr-processing-state-05
