Repository quark-engine/quark-engine, pull requests merged in 2022-11, with the labels that each got.

#413 Add quark script case for CWE 319
  docs/build/doctrees/addRules.doctree
  docs/build/doctrees/coding_style.doctree
  docs/build/doctrees/contribution.doctree
  docs/build/doctrees/dev.doctree
  docs/build/doctrees/dev_index.doctree
  docs/build/doctrees/environment.pickle
  docs/build/doctrees/index.doctree
  docs/build/doctrees/install.doctree
  docs/build/html/_static/css/badge_only.css
  docs/build/html/_static/css/theme.css
  docs/build/html/addRules.html
  docs/build/html/coding_style.html
  docs/build/html/contribution.html
  docs/build/html/dev.html
  docs/build/html/dev_index.html
  docs/build/html/genindex.html
  docs/build/html/index.html
  docs/build/html/install.html
  docs/build/html/search.html
  docs/build/html/searchindex.js
  docs/source/quark_script.rst
Labels: pr-processing-state-06

#414 Fix typo found on Quark web report
  README.md
  quark/cli.py
  quark/utils/graph.py
  quark/webreport/analysis_report_layout.html
Labels: pr-processing-state-06

#422 Add Quick Start to Quark Script documentation
  docs/build/doctrees/addRules.doctree
  docs/build/doctrees/coding_style.doctree
  docs/build/doctrees/contribution.doctree
  docs/build/doctrees/dev.doctree
  docs/build/doctrees/dev_index.doctree
  docs/build/doctrees/environment.pickle
  docs/build/doctrees/index.doctree
  docs/build/doctrees/install.doctree
  docs/build/html/_static/css/theme.css
  docs/build/html/index.html
  docs/build/html/objects.inv
  docs/build/html/searchindex.js
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05

#419 Fix web report typo and darken radar chart grid lines
  README.md
  quark/webreport/analysis_report_layout.html
  quark/webreport/generate.py
Labels: pr-processing-state-06

#424 Update README to introduce Quark Script only
  README.md
  docs/build/doctrees/addRules.doctree
  docs/build/doctrees/coding_style.doctree
  docs/build/doctrees/contribution.doctree
  docs/build/doctrees/dev.doctree
  docs/build/doctrees/dev_index.doctree
  docs/build/doctrees/environment.pickle
  docs/build/doctrees/index.doctree
  docs/build/doctrees/install.doctree
  docs/build/html/_sources/index.rst.txt
  docs/build/html/_static/basic.css
  docs/build/html/_static/css/badge_only.css
  docs/build/html/_static/css/theme.css
  docs/build/html/addRules.html
  docs/build/html/coding_style.html
  docs/build/html/contribution.html
  docs/build/html/dev.html
  docs/build/html/dev_index.html
  docs/build/html/genindex.html
  docs/build/html/index.html
  docs/build/html/install.html
  docs/build/html/objects.inv
  docs/build/html/search.html
  docs/build/html/searchindex.js
  docs/source/index.rst
  docs/source/quark_reports.rst
Labels: documentation, pr-processing-state-05

#428 Add Quark Script to detect CWE-327
  docs/build/doctrees/environment.pickle
  docs/build/html/index.html
  docs/build/html/searchindex.js
  docs/source/quark_script.rst
Labels: quark rule, work-in-progress, pr-processing-state-05

#429 Add CWE-327 showcase link to README
  README.md
Labels: pr-processing-state-05

#431 Update version number to v22.11.1
  quark/__init__.py
Labels: pr-processing-state-07
