Repository quark-engine/quark-engine, pull requests merged in 2022-12, with the labels that each got.

#434 Add Quark Script to detect CWE-20
  docs/build/doctrees/environment.pickle
  docs/build/html/searchindex.js
  docs/source/quark_script.rst
  quark/script/__init__.py
  tests/script/test_script.py
Labels: pr-processing-state-05

#435 Add CWE-20 showcase link to README
  README.md
Labels: pr-processing-state-06

#438 Remove dependency kaleido temporarily
  .github/workflows/smoke_test.yml
  quark/core/quark.py
  setup.py
Labels: dependencies, pr-processing-state-06

#436 Add quark script case for CWE 79
  docs/build/doctrees/addRules.doctree
  docs/build/doctrees/coding_style.doctree
  docs/build/doctrees/contribution.doctree
  docs/build/doctrees/dev.doctree
  docs/build/doctrees/dev_index.doctree
  docs/build/doctrees/environment.pickle
  docs/build/doctrees/index.doctree
  docs/build/doctrees/install.doctree
  docs/build/html/genindex.html
  docs/build/html/index.html
  docs/build/html/objects.inv
  docs/build/html/searchindex.js
  docs/source/quark_script.rst
  quark/script/__init__.py
Labels: quark rule, work-in-progress, pr-processing-state-04

#443 Update version number to v22.12.1
  quark/__init__.py
Labels: pr-processing-state-05
