Repository quark-engine/quark-engine, pull requests merged in 2023-12, with the labels that each got.

#586 Remove pandas and kaleido from dependencies
  Pipfile
  Pipfile.lock
  debian/control
  quark/core/quark.py
  setup.py
  tests/core/test_quark.py
Labels: dependencies, pr-processing-state-05

#587 Fix the inconsistances of formats in the docs for Quark Script
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05

#590 Add method reference for select_label_menu
  docs/source/quark_method_reference.rst
Labels: documentation, pr-processing-state-05

#591 Add quark script for CWE-601
  docs/source/quark_script.rst
Labels: work-in-progress, pr-processing-state-06

#593 Add document link of CWE-601 showcase to the README
  README.md
Labels: pr-processing-state-04

#595 Update version number to v23.12.1
  quark/__init__.py
Labels: pr-processing-state-05
