Repository quark-engine/quark-engine, pull requests merged in 2023-04, with the labels that each got.

#496 Add method reference for _evaluate_method in document
  docs/source/quark_method_reference.rst
Labels: documentation, pr-processing-state-04

#499 remove deprecated codecov package
  .github/workflows/pytest.yml
  .travis.yml
Labels: pr-processing-state-05

#487 Add property `receivers` to Quark Engine.
  quark/core/apkinfo.py
  quark/core/interface/baseapkinfo.py
  quark/core/rzapkinfo.py
  tests/core/test_apkinfo.py
Labels: pr-processing-state-05

#497 Add method reference for check_parameter_on_single_method
  docs/source/quark_method_reference.rst
Labels: documentation, pr-processing-state-05

#502 Update version number to v23.4.1
  quark/__init__.py
Labels: pr-processing-state-05
