Repository quark-engine/quark-engine, pull requests merged in 2023-05, with the labels that each got.

#503 Add quark script for CWE-88
  docs/source/quark_script.rst
Labels: pr-processing-state-05

#506 Fix smoke test error due to image macos 10 being deprecated.
  .github/workflows/smoke_test.yml
Labels: pr-processing-state-05

#500 Add quark script case for CWE-925.
  docs/source/quark_script.rst
  quark/script/__init__.py
  tests/script/test_script.py
Labels: work-in-progress, pr-processing-state-06

#507 Add document link of CWE-925 showcase to the README
  README.md
Labels: pr-processing-state-04

#508 Exclude the Quark tests from installation.
  setup.py
Labels: pr-processing-state-05

#509 Add method reference of check_parameter
  docs/source/quark_method_reference.rst
Labels: documentation, pr-processing-state-05

#511 Add method reference of check_parameter_values
  docs/source/quark_method_reference.rst
Labels: documentation, pr-processing-state-05

#517 Install packages with pip instead of Setuptools in CI
  .github/workflows/pytest.yml
  .github/workflows/smoke_test.yml
Labels: pr-processing-state-05

#514 Add Quark Script CWE-73
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05

#518 Add document link of CWE-73 showcase to the README
  README.md
Labels: pr-processing-state-05
