Repository quark-engine/quark-engine, pull requests merged in 2023-06, with the labels that each got.

#520 Add method reference for check_sequence
  docs/source/quark_method_reference.rst
Labels: documentation, pr-processing-state-05

#519 Add quark script for CWE-78
  docs/source/quark_script.rst
Labels: pr-processing-state-05

#521 Add method reference for run in document
  docs/source/quark_method_reference.rst
Labels: documentation, pr-processing-state-05

#522 Add document link of CWE-78 showcase to the README
  README.md
Labels: documentation, pr-processing-state-06

#525 Rivise the description of CWE-78
  docs/source/quark_script.rst
Labels: bug, documentation, pr-processing-state-06

#524 Update version number to v23.6.1
  quark/__init__.py
Labels: pr-processing-state-05
