Repository quark-engine/quark-engine, pull requests merged in 2023-02, with the labels that each got.

#460 Add quark script for CWE 22
  Pipfile
  docs/source/quark_script.rst
  quark/script/__init__.py
  setup.py
  tests/script/test_script.py
Labels: pr-processing-state-04

#461 Add document link of CWE-22 showcase to the README
  README.md
Labels: pr-processing-state-05

#463 New document file quark_method_reference.rst and new instruction of find_previous_method in document.
  docs/source/index.rst
  docs/source/quark_method_reference.rst
Labels: documentation, work-in-progress, pr-processing-state-06

#465 New instruction of find_intersection in document.
  docs/source/quark_method_reference.rst
Labels: documentation, work-in-progress, pr-processing-state-04

#472 Update version number to v23.2.1
  quark/__init__.py
Labels: pr-processing-state-05
