Repository quark-engine/quark-engine, pull requests merged in 2023-11, with the labels that each got.

#569 Add the method reference for wrapper_lookup to the document
  docs/source/quark_method_reference.rst
Labels: documentation, pr-processing-state-05

#570 Add method reference for show_comparison_graph in the document
  docs/source/quark_method_reference.rst
Labels: documentation, pr-processing-state-04

#572 Add quark script for CWE-502
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05

#576 Add document link of CWE-502 showcase to the README
  README.md
Labels: documentation

#579 Change the source of radare2 in CI
  .github/workflows/pytest.yml
Labels: pr-processing-state-05

#577 Add the method reference for call_graph
  docs/source/quark_method_reference.rst
Labels: documentation, pr-processing-state-05

#575 Make the importation for Ciphey optional
  Pipfile
  Pipfile.lock
  quark/script/ciphey.py
  tests/script/test_ciphey.py
Labels: dependencies, pr-processing-state-06

#581 Add the command `freshquark` to the Dockerfile
  Dockerfile
Labels: pr-processing-state-05
