Repository quark-engine/quark-engine, pull requests merged in 2023-08, with the labels that each got.

#534 Add method reference for show_summary_report in document
  docs/source/quark_method_reference.rst
Labels: documentation, pr-processing-state-04

#535 Add quark script for CWE-117
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05

#536 Visual Quark Scripts Program: Web design layout
  docs/source/index.rst
  docs/source/visual_quark_script_program.rst
Labels: documentation, work-in-progress, pr-processing-state-04

#537 Fix image link error in document of Visual Quark Script
  docs/source/visual_quark_script_program.rst
Labels: pr-processing-state-05

#539 Add quark script for CWE-940
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05

#540 Add document link of CWE-940 showcase to the README
  README.md
Labels: pr-processing-state-05

#542 Add document link of CWE-117 showcase to the README
  README.md
Labels: pr-processing-state-05
