Repository quark-engine/quark-engine, pull requests merged in 2023-10, with the labels that each got.

#557 Add method reference for show_call_graph in the document
  docs/source/quark_method_reference.rst
Labels: documentation, pr-processing-state-05

#559 Set dependencies for readthedocs
  .readthedocs.yaml
  docs/requirements.txt
Labels: pr-processing-state-05

#556 Fix GitHub security alerts by escalating versions of dependent packages.
  Pipfile
  Pipfile.lock
Labels: dependencies, pr-processing-state-05

#495 Add analysis library for radare2 v5.8.8
  .github/workflows/pytest.yml
  Pipfile
  quark/cli.py
  quark/core/axmlreader/__init__.py
  quark/core/quark.py
  quark/core/r2apkinfo.py
  setup.py
  tests/core/test_apkinfo.py
  tests/core/test_axmlreader.py
Labels: pr-processing-state-06

#560 Add method reference for show_rule_classification in the document
  docs/source/quark_method_reference.rst
Labels: documentation, pr-processing-state-04

#562 Add the summary of the quark module to the document
  docs/source/quark_method_reference.rst
Labels: documentation, pr-processing-state-05

#566 Fix invalid links in the method reference for the quark module
  docs/source/quark_method_reference.rst
Labels: documentation, pr-processing-state-05

#565 Fix typo in quark script for CWE-749 and CWE-780
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05

#561 Fix keyword matching in fifth stage of quark analysis
  .github/workflows/smoke_test.yml
  quark/core/quark.py
  tests/core/test_quark.py
Labels: pr-processing-state-05
