Repository quark-engine/quark-engine, pull requests merged in 2024-05, with the labels that each got.

#638 Update version information to v24.5.1
  debian/changelog
  debian/control
  docs/source/conf.py
  quark/__init__.py
Labels: pr-processing-state-05

#642 Optimize the CWE-20 document
  docs/source/quark_script.rst
Labels: pr-processing-state-05

#643 Modify CWE-798 code
  docs/source/quark_script.rst
Labels: pr-processing-state-05

#644 Optimize the CWE-73 document
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-04

#647 Fix failure installation of an upstream package in CI
  .github/workflows/pytest.yml
  .github/workflows/smoke_test.yml
  Pipfile
Labels: pr-processing-state-04

#651 Add the threshold in codecov.yml.
  codecov.yml
Labels: pr-processing-state-05

#649 Optimize the CWE-78 document
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-04
