Repository quark-engine/quark-engine, pull requests merged in 2024-04, with the labels that each got.

#624 Update the release timing in the document
  docs/source/organization.rst
Labels: documentation

#625 Update version information to v24.4.1
  debian/changelog
  debian/control
  docs/source/conf.py
  quark/__init__.py
Labels: pr-processing-state-06

#629 Optimize CWE-327 document
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-04

#633 Optimize CWE 22 document
  docs/source/quark_script.rst
Labels: pr-processing-state-05

#634 Optimize CWE 23 document
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-04

#636 Fix the CI failure with the Mac OS smoke test.
  .github/workflows/smoke_test.yml
Labels: pr-processing-state-05
