Repository quark-engine/quark-engine, pull requests merged in 2024-10, with the labels that each got.

#698 Add Quark Agent's Auto-Suggestion preview to README
  README.md
Labels: pr-processing-state-05

#690 Update analysis library for Rizin v0.7.3
  .github/workflows/pytest.yml
  quark/core/axmlreader/__init__.py
  quark/core/axmlreader/radare2/__init__.py
  quark/core/axmlreader/radare2/axml_definition
  quark/core/axmlreader/rizin/__init__.py
  quark/core/axmlreader/rizin/axml_definition
  quark/core/quark.py
  quark/core/rzapkinfo.py
  quark/evaluator/pyeval.py
  quark/utils/tools.py
  setup.py
  tests/core/test_apkinfo.py
  tests/core/test_rzapkinfo.py
Labels: pr-processing-state-06

#700 Optimize the document of Quark Script CWE-338
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05

#702 Optimize the document of Quark Script CWE-489
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05

#704 Optimize the document of Quark Script CWE-532
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05
