Repository quark-engine/quark-engine, pull requests merged in 2024-11, with the labels that each got.

#709 Update radare2 version to 5.9.0 in CI
  .github/workflows/pytest.yml
Labels: dependencies, pr-processing-state-05

#707 Update version information to v24.11.1
  debian/changelog
  debian/control
  docs/source/conf.py
  quark/__init__.py
Labels: pr-processing-state-05

#712 Replace deprecated package and change syntax to solve issues in python 3.12
  .github/workflows/pytest.yml
  .github/workflows/smoke_test.yml
  Pipfile
  Pipfile.lock
  quark/core/axmlreader/__init__.py
  quark/script/frida/__init__.py
  quark/utils/output.py
  quark/webreport/generate.py
  tests/webreport/test_generate.py
Labels: dependencies, pr-processing-state-05

#711 Optimize the document of Quark Script CWE-940
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05

#715 Update minimum python version to 3.10
  .github/workflows/pytest.yml
  .github/workflows/smoke_test.yml
  .readthedocs.yaml
  .travis.yml
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  codecov.yml
  docs/source/quark.script.rst
  docs/source/quark_script.rst
  quark/script/ares.py
  quark/script/ciphey.py
  setup.py
  tests/script/test_ares.py
Labels: dependencies

#717 Optimize the document of Quark Script CWE-312
  docs/source/quark_script.rst
Labels: pr-processing-state-05
