Repository quark-engine/quark-engine, pull requests merged in 2024-08, with the labels that each got.

#666 Improve getParamValue API for More Accurate Parameter Extraction from Smali Code
  quark/script/__init__.py
  quark/utils/tools.py
  tests/script/test_script.py
Labels: pr-processing-state-05

#667 Update quark_script_agent.rst
  docs/source/quark_script_agent.rst
Labels: documentation

#615 Update the badges in the README.md
  README.md
Labels: pr-processing-state-05

#670 Introduce the Quark Agent
  .github/workflows/pytest.yml
  docs/source/index.rst
  docs/source/quark.agent.rst
  docs/source/quark.rst
  docs/source/quark_agent.rst
  docs/source/quark_reports.rst
  quark/agent/__init__.py
  quark/agent/agentTools.py
  quark/agent/prompts.py
  quark/agent/quarkAgent.py
  setup.py
  tests/agent/conftest.py
  tests/agent/test_agentTools.py
  tests/agent/test_quarkAgent.py
Labels: documentation

#677 Optimize the CWE-88 document
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-07

#674 Update dependency versions in pipenv environment
  Pipfile
  Pipfile.lock
  docs/requirements.txt
Labels: pr-processing-state-05

#676 Fix typos and configuration omissions for the document
  .readthedocs.yaml
  docs/requirements.txt
  docs/source/faq.rst
  docs/source/quark.core.rst
  docs/source/quark_inside_index.rst
  docs/source/quark_method_reference.rst
  docs/source/quark_mit_program.rst
  docs/source/quark_script.rst
  quark/script/objection.py
Labels: documentation, pr-processing-state-05

#678 Introducing the Quark Agent Web Interface
  README.md
  quark/agent/agentTools.py
  quark/agent/prompts.py
  quark/agent/quarkAgentWeb.py
  quark/agent/static/css/style.css
  quark/agent/static/images/quark-logo.png
  quark/agent/static/js/chatbox.js
  quark/agent/templates/artificial-intelligence.png
  quark/agent/templates/index.html
  setup.py
  tests/agent/test_agentTools.py
Labels: pr-processing-state-05
