Repository quark-engine/quark-engine, pull requests merged in 2024-09, with the labels that each got.

#684 Update version information to v24.9.1
  debian/changelog
  debian/control
  docs/source/conf.py
  quark/__init__.py
Labels: pr-processing-state-05

#685 Introduce the second showcase of Quark Agent
  docs/source/index.rst
  docs/source/quark.agent.rst
  docs/source/quark_agent.rst
  docs/source/quark_script_agent.rst
  quark/agent/agentTools.py
  quark/agent/quarkAgent.py
  quark/core/analysis.py
  tests/agent/test_agentTools.py
Labels: documentation, pr-processing-state-05

#689 Use getArguments() instead of getParamValues() in CWE showcases
  docs/source/quark_script.rst
Labels: documentation

#691 Optimize the document of Quark Script CWE-117
  docs/source/quark_script.rst
Labels: documentation, issue-processing-state-03

#680 Update minimum python version to 3.9
  .github/workflows/pytest.yml
  .github/workflows/smoke_test.yml
  .readthedocs.yaml
  .travis.yml
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  docs/source/quark_script.rst
  setup.py
Labels: dependencies, pr-processing-state-06

#693 Add Quark Agent workflow feature preview to README
  README.md
Labels: pr-processing-state-05

#694 Add 'Stay Connected' section to README.md
  README.md
Labels: pr-processing-state-05
