Repository quark-engine/quark-engine, pull requests merged in 2024-03, with the labels that each got.

#614 Optimize the CWE-312 document
  docs/source/quark_script.rst
Labels: pr-processing-state-04

#617 Optimize the CWE-921 and CWE-89 document
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05

#619 Fix images in CWE-94 and CWE-926 document
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-06

#621 Optimize CWE-749 and CWE-780 document
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05
