Repository quark-engine/quark-engine, pull requests merged in 2024-12, with the labels that each got.

#720 Replace importlib_resources with builtin module of Python
  .github/workflows/pytest.yml
  .github/workflows/smoke_test.yml
  Pipfile
  Pipfile.lock
  quark/core/axmlreader/__init__.py
  quark/script/frida/__init__.py
  quark/webreport/generate.py
  tests/webreport/test_generate.py
Labels: dependencies, pr-processing-state-05

#722 Optimize the document of Quark Script CWE-798
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05

#723 Optimize the document of Quark Script CWE-921
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05

#724 Optimize the document of Quark Script CWE-94
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05

#726 Update version information to v25.1.1
  debian/changelog
  debian/control
  docs/source/conf.py
  quark/__init__.py
Labels: pr-processing-state-05
