Repository quark-engine/quark-engine, pull requests merged in 2025-01, with the labels that each got.

#727 Optimize the document of Quark Script CWE-20
  docs/source/quark_script.rst
Labels: documentation, pr-processing-state-05

#697 Add a Shuriken-based core library
  .github/workflows/pytest.yml
  .github/workflows/smoke_test.yml
  quark/cli.py
  quark/core/apkinfo.py
  quark/core/axmlreader/__init__.py
  quark/core/axmlreader/python.py
  quark/core/axmlreader/radare2/axml_definition
  quark/core/axmlreader/rizin/axml_definition
  quark/core/interface/baseapkinfo.py
  quark/core/quark.py
  quark/core/r2apkinfo.py
  quark/core/rzapkinfo.py
  quark/core/shurikenapkinfo.py
  quark/core/struct/methodobject.py
  setup.py
  tests/core/test_apkinfo.py
  tests/core/test_axmlreader.py
Labels: enhancement, work-in-progress

#730 Optimize the document of Quark Script CWE-22
  docs/source/quark_script.rst
Labels: documentation
